language: python

python:
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install tensorflow
  - ./download_engame_tablebases.sh

script:
  - python -m unittest discover -s tests -t tests

notifications:
  email: false
